# 简化版比特币网络配置文件
app:
  name: "Simplied Bitcoin Network"
  version: "1.0.0"
  debug: false
  log_level: "info"

# 网络配置
network:
  # 监听端口
  port: 8080
  # 最大连接数
  max_connections: 50
  # 连接超时时间（秒）
  connection_timeout: 30
  # 心跳间隔（秒）
  heartbeat_interval: 60
  # 种子节点
  seeds:
    - "127.0.0.1:8081"
    - "127.0.0.1:8082"

# RPC配置
rpc:
  # RPC监听端口
  port: 8545
  # 启用CORS
  enable_cors: true
  # API限流（请求/分钟）
  rate_limit: 1000
  # 启用认证
  enable_auth: false
  # 认证密钥
  auth_key: "your-secret-key-here"

# 挖矿配置
mining:
  # 启用挖矿
  enabled: false
  # 矿工地址
  miner_address: ""
  # 挖矿线程数（0=自动检测）
  threads: 0
  # 目标出块时间（秒）
  block_time: 10

# 区块链配置
blockchain:
  # 数据目录
  data_dir: "./data"
  # 最大区块大小（字节）
  max_block_size: 1048576  # 1MB
  # 创世区块难度
  genesis_difficulty: 0x1d00ffff
  # 难度调整周期（区块数）
  difficulty_adjustment_interval: 2016
  # 最大供应量
  max_supply: 21000000

# 数据库配置
database:
  # 数据库类型
  type: "bolt"
  # 数据库文件路径
  path: "./data/blockchain.db"
  # 缓存大小（MB）
  cache_size: 100
  # 批量写入大小
  batch_size: 1000

# Web界面配置
web:
  # 静态文件目录
  static_dir: "./web"
  # 模板目录
  template_dir: "./web/templates"
  # 启用gzip压缩
  enable_gzip: true

# 日志配置
logging:
  # 日志级别: debug, info, warn, error
  level: "info"
  # 日志格式: json, text
  format: "text"
  # 日志输出: stdout, stderr, file
  output: "stdout"
  # 日志文件路径（当output为file时）
  file_path: "./logs/bitcoin-network.log"
  # 日志文件最大大小（MB）
  max_size: 100
  # 保留的日志文件数量
  max_backups: 7
  # 日志文件保留天数
  max_age: 30

# 安全配置
security:
  # TLS配置
  tls:
    enabled: false
    cert_file: ""
    key_file: ""
  # 最大请求大小（字节）
  max_request_size: 10485760  # 10MB
  # 请求超时时间（秒）
  request_timeout: 30